"""Native C / LLVM Code Generation Backend for NOVA.

Lowers validated AST / HIR into optimized C99 / LLVM-compatible code
and invokes the system clang compiler to emit native machine executables.
"""
from __future__ import annotations

import os
import subprocess
import tempfile
from typing import Any, Optional

from verifier.refspec import ast as a
from verifier.refspec.check import CheckResult


RUNTIME_HEADER = """
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include <time.h>

// NOVA Primitive Types
typedef int64_t nova_int;
typedef bool nova_bool;
typedef const char* nova_string;

// Capability System Structs
typedef struct { void* handle; } nova_runtime_t;
typedef struct { void* handle; } nova_clock_t;
typedef struct { void* handle; } nova_fs_t;
typedef struct { void* handle; } nova_net_t;

// Builtin Runtime Functions
static inline void nova_print(nova_runtime_t rt, nova_string msg) {
    (void)rt;
    printf("%s\\n", msg ? msg : "");
}

static inline nova_clock_t nova_runtime_clock(nova_runtime_t rt) {
    (void)rt;
    nova_clock_t c = { .handle = NULL };
    return c;
}

static inline nova_int nova_clock_now(nova_clock_t c) {
    (void)c;
    struct timespec ts;
    clock_gettime(CLOCK_REALTIME, &ts);
    return (nova_int)(ts.tv_sec * 1000LL + ts.tv_nsec / 1000000LL);
}

static inline nova_string nova_int_to_str(nova_int val) {
    char* buf = (char*)malloc(32);
    snprintf(buf, 32, "%lld", (long long)val);
    return buf;
}

static inline nova_string nova_str_concat(nova_string s1, nova_string s2) {
    if (!s1) s1 = "";
    if (!s2) s2 = "";
    size_t len1 = strlen(s1);
    size_t len2 = strlen(s2);
    char* res = (char*)malloc(len1 + len2 + 1);
    memcpy(res, s1, len1);
    memcpy(res + len1, s2, len2);
    res[len1 + len2] = '\\0';
    return res;
}
"""


class CCodeGen:
    def __init__(self, check_result: CheckResult) -> None:
        self.check_result = check_result
        self.output_lines: list[str] = []
        self.indent_level = 0

    def emit(self, line: str = "") -> None:
        if line:
            self.output_lines.append("    " * self.indent_level + line)
        else:
            self.output_lines.append("")

    def indent(self) -> None:
        self.indent_level += 1

    def dedent(self) -> None:
        self.indent_level = max(0, self.indent_level - 1)

    def generate(self) -> str:
        self.emit("// Generated by NOVA Native Compiler")
        self.emit(RUNTIME_HEADER)
        self.emit()

        # Forward declarations of structs
        self.emit("// Forward declarations")
        for struct_info in self.check_result.structs.values():
            self.emit(f"typedef struct nova_struct_{struct_info.name} nova_struct_{struct_info.name};")
        self.emit()

        # Struct definitions
        for struct_info in self.check_result.structs.values():
            self.emit(f"struct nova_struct_{struct_info.name} {{")
            self.indent()
            for fld_name, fld_ty in struct_info.fields.items():
                c_ty = self.map_type_name(str(fld_ty))
                self.emit(f"{c_ty} {fld_name};")
            self.dedent()
            self.emit("};")
            self.emit()

        # Function forward declarations
        for fn_info in self.check_result.fns.values():
            decl = fn_info.decl
            ret_ty = self.map_type_name(decl.ret.name if decl.ret and hasattr(decl.ret, 'name') else 'Int')
            param_sig = self.gen_params(decl.params)
            self.emit(f"{ret_ty} nova_fn_{decl.name}({param_sig});")
        self.emit()

        # Function definitions
        for fn_info in self.check_result.fns.values():
            self.gen_function(fn_info.decl)

        # C Main entrypoint
        self.emit()
        self.emit("int main(int argc, char** argv) {")
        self.indent()
        self.emit("(void)argc; (void)argv;")
        self.emit("nova_runtime_t rt = { .handle = NULL };")
        if "main" in self.check_result.fns:
            self.emit("nova_int code = nova_fn_main(rt);")
            self.emit("return (int)code;")
        else:
            self.emit("return 0;")
        self.dedent()
        self.emit("}")

        return "\n".join(self.output_lines)

    def map_type_name(self, name: str) -> str:
        if name in ("Int", "int"):
            return "nova_int"
        elif name in ("Bool", "bool"):
            return "nova_bool"
        elif name in ("String", "str"):
            return "nova_string"
        elif name == "Runtime":
            return "nova_runtime_t"
        elif name == "Clock":
            return "nova_clock_t"
        elif name in self.check_result.structs:
            return f"nova_struct_{name}"
        return "nova_int"

    def gen_params(self, params: list[a.Param]) -> str:
        if not params:
            return "void"
        parts = []
        for p in params:
            c_ty = self.map_type_name(p.ty.name if hasattr(p.ty, 'name') else 'Int')
            parts.append(f"{c_ty} {p.name}")
        return ", ".join(parts)

    def gen_function(self, decl: a.FnDecl) -> None:
        ret_ty = self.map_type_name(decl.ret.name if decl.ret and hasattr(decl.ret, 'name') else 'Int')
        param_sig = self.gen_params(decl.params)
        self.emit(f"{ret_ty} nova_fn_{decl.name}({param_sig}) {{")
        self.indent()

        if decl.body:
            if isinstance(decl.body, a.Block):
                body_code = self.gen_block_body(decl.body)
                self.emit(body_code)
            else:
                expr_c = self.gen_expr(decl.body)
                self.emit(f"return {expr_c};")
        else:
            self.emit("return 0;")

        self.dedent()
        self.emit("}")
        self.emit()

    def gen_block_body(self, block: a.Block) -> str:
        lines = []
        for stmt in block.stmts:
            if isinstance(stmt, a.Let):
                init_val = self.gen_expr(stmt.value) if stmt.value else "0"
                lines.append(f"__auto_type {stmt.name} = {init_val};")
            elif isinstance(stmt, a.Assign):
                val = self.gen_expr(stmt.value)
                lines.append(f"{stmt.name} = {val};")
            elif isinstance(stmt, a.While):
                cond = self.gen_expr(stmt.cond)
                body = self.gen_block_body(stmt.body) if isinstance(stmt.body, a.Block) else self.gen_expr(stmt.body)
                lines.append(f"while ({cond}) {{\n{body}\n}}")
            elif isinstance(stmt, a.Expr):
                expr_c = self.gen_expr(stmt)
                lines.append(f"{expr_c};")

        if block.tail:
            if isinstance(block.tail, a.If):
                cond = self.gen_expr(block.tail.cond)
                then_body = self.gen_block_body(block.tail.then) if isinstance(block.tail.then, a.Block) else f"return {self.gen_expr(block.tail.then)};"
                else_body = self.gen_block_body(block.tail.els) if isinstance(block.tail.els, a.Block) else (f"return {self.gen_expr(block.tail.els)};" if block.tail.els else "return 0;")
                lines.append(f"if ({cond}) {{\n{then_body}\n    }} else {{\n{else_body}\n    }}")
            else:
                res_c = self.gen_expr(block.tail)
                lines.append(f"return {res_c};")
        else:
            lines.append("return 0;")

        return "\n".join(f"    {l}" for l in lines)

    def gen_expr(self, expr: a.Expr) -> str:
        if isinstance(expr, a.IntLit):
            return str(expr.value)
        elif isinstance(expr, a.StrLit):
            escaped = expr.value.replace('"', '\\"')
            return f'"{escaped}"'
        elif isinstance(expr, a.BoolLit):
            return "true" if expr.value else "false"
        elif isinstance(expr, a.Var):
            return expr.name
        elif isinstance(expr, a.Binary):
            l = self.gen_expr(expr.left)
            r = self.gen_expr(expr.right)
            if expr.op == "+":
                return f"({l} + {r})"
            elif expr.op == "-":
                return f"({l} - {r})"
            elif expr.op == "*":
                return f"({l} * {r})"
            elif expr.op == "/":
                return f"({l} / {r})"
            elif expr.op == "==":
                return f"({l} == {r})"
            elif expr.op == "!=":
                return f"({l} != {r})"
            elif expr.op == "<":
                return f"({l} < {r})"
            elif expr.op == "<=":
                return f"({l} <= {r})"
            elif expr.op == ">":
                return f"({l} > {r})"
            elif expr.op == ">=":
                return f"({l} >= {r})"
            return f"({l} {expr.op} {r})"
        elif isinstance(expr, a.Call):
            if isinstance(expr.callee, a.Var):
                callee_name = expr.callee.name
                args_c = ", ".join(self.gen_expr(arg) for arg in expr.args)
                return f"nova_fn_{callee_name}({args_c})"
            callee_c = self.gen_expr(expr.callee)
            args_c = ", ".join(self.gen_expr(arg) for arg in expr.args)
            return f"{callee_c}({args_c})"
        elif isinstance(expr, a.MethodCall):
            recv_c = self.gen_expr(expr.recv)
            if expr.op == "print":
                arg_c = self.gen_expr(expr.args[0]) if expr.args else '""'
                return f"nova_print({recv_c}, {arg_c})"
            elif expr.op == "clock":
                return f"nova_runtime_clock({recv_c})"
            elif expr.op == "now":
                return f"nova_clock_now({recv_c})"
            args_c = ", ".join(self.gen_expr(arg) for arg in expr.args)
            return f"nova_method_{expr.op}({recv_c}{', ' + args_c if args_c else ''})"
        elif isinstance(expr, a.FieldAccess):
            recv_c = self.gen_expr(expr.recv)
            return f"({recv_c}.{expr.field})"
        elif isinstance(expr, a.StructLit):
            fld_inits = []
            for fld_name, fld_expr in expr.fields:
                fld_val = self.gen_expr(fld_expr)
                fld_inits.append(f".{fld_name} = {fld_val}")
            return f"(nova_struct_{expr.name}){{ {', '.join(fld_inits)} }}"
        elif isinstance(expr, a.If):
            cond = self.gen_expr(expr.cond)
            then_c = self.gen_expr(expr.then)
            else_c = self.gen_expr(expr.els) if expr.els else "0"
            return f"({cond} ? {then_c} : {else_c})"
        elif isinstance(expr, a.Block):
            if not expr.stmts and expr.tail:
                return self.gen_expr(expr.tail)
            return "0"
        return "0"


def compile_to_native(check_result: CheckResult, output_binary_path: str, opt_level: str = "-O3") -> bool:
    """Compile check_result into native binary using clang."""
    codegen = CCodeGen(check_result)
    c_source = codegen.generate()

    with tempfile.NamedTemporaryFile(suffix=".c", delete=False) as tf:
        tf.write(c_source.encode("utf-8"))
        c_path = tf.name

    try:
        cmd = ["clang", opt_level, c_path, "-o", output_binary_path]
        res = subprocess.run(cmd, capture_output=True, text=True)
        if res.returncode != 0:
            print(f"Compilation error:\n{res.stderr}")
            return False
        return True
    finally:
        if os.path.exists(c_path):
            os.remove(c_path)
